server:
  port: 8083

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

security:
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: http://authentication:9999/uaa/user

management:
  security:
    enabled: false
    
