server:
  port: 8084
  
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

management:
  security:
    enabled: false
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
     