info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    helloworld:
      path: /helloworld/**
    currencyconverter:
      path: /currencyconverter/**
    transactionservice:
      path: /transactionservice/**

server:
  port: 8765
  
security:
  basic:
    enabled: false
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
